### ISSUE TITLE
CrazyEnvoy Is it up to date error

### ISSUE THREAD

**Issue by bobbyjo31** [badbones69/Crazy-Envoy#46]
Hello recently with crazyenvoy it wont enable and it shows this error in logs
```[00:34:00] [Server thread/INFO]: [CrazyEnvoy] Enabling CrazyEnvoy v1.2.8.3
[00:34:00] [Server thread/ERROR]: Error occurred while enabling CrazyEnvoy v1.2.8.3 (Is it up to date?)
java.lang.IllegalStateException: No API implementation set. Is Holographic Displays enabled?
	at com.gmail.filoghost.holographicdisplays.api.internal.BackendAPI.getImplementation(BackendAPI.java:36) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.api.HologramsAPI.registerPlaceholder(HologramsAPI.java:73) ~[?:?]
	at me.badbones69.envoy.multisupport.HolographicSupport.registerPlaceHolders(HolographicSupport.java:23) ~[?:?]
	at me.badbones69.envoy.Main.onEnable(Main.java:57) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[00:34:00] [Server thread/INFO]: [CrazyEnvoy] Disabling CrazyEnvoy v1.2.8.3
```

I have updated it and holographicdisplays and nothing. I dont know what to do.

**Comment by badbones69** [comment]
@bobbyjo31 your not on the newest CEv. The newest is [v1.3.9](https://github.com/badbones69/Crazy-Envoy/releases/tag/v1.3.9). Update and then see if it fixes it.
